### ISSUE TITLE
The Big V1.5 Task List

### ISSUE THREAD

**Issue by 20kdc** [20kdc/gabien-app-r48#57]
common:
- [x] AtlasBuilder
- [x] Stabilize BadGPU / release "frozen" gabien-natives package
- [x] Mechanism to "keep natives tracable"; once the package is released, that release is what ships
- [x] FontManager removal / migration to theming
 - As done as it can be without tearing up everything. There's some iffy stuff with label init but no good way to fix it.

r48:
- [x] Finish removing FormatSyntax
- [x] Figure out why RXP `iterate_actor` is misbehaving
- [x] Make the ODB view stop spamming string renders
- [x] Why is `(help)` in the REPL an instafreeze
- [x] Fix tileset rebuilds being the performance nightmare of some backends
- [x] Finish translation page sorting
- [x] Tile rendering performance improvements (see: AtlasBuilder)
- [x] Android performance review once tile rendering is cleaned up
 - People have told me it's fine so it's probably fine
- [x] Image editor filename bug
- [x] String finder

29th September:

- [x] Light theme No Map icon bug

30th September:

- [x] Test, test, test

1st October:

- [x] Actually release v1.5
